services:
  ksmb:
    build: .
    container_name: ksmb
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ksmb.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.ksmb.entrypoints=websecure"
      - "traefik.http.routers.ksmb.tls.certresolver=le"
      - "traefik.http.services.ksmb.loadbalancer.server.port=${PORT}"
      - "traefik.http.middlewares.podatnik-hsts.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.podatnik-hsts.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.podatnik-hsts.headers.stsPreload=true"
      - "traefik.http.routers.podatnik.middlewares=podatnik-hsts@docker"
    networks:
      - web
    expose:
      - "${PORT}"

networks:
  web:
    external: true
